name: Keep Streamlit Alive

on:
  schedule:
    - cron: '0 */3 * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Hit Streamlit App
        run: curl -I -s https://tugas-hac-rivaldi.streamlit.app/
